Project1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ShoeStore.urls")),
    path('vendas/',include("vendas.urls")),
    path("compras/",include("compras.urls")),
]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

vendas/api/urls.py
from django.urls import path

from .views import ProdutoDetalheView, criar_venda

api_urlpatterns = [
    path(
        "api/produtos/<int:id>",
        ProdutoDetalheView.as_view(),
        name="produto_detalhe",
    ),
    path(
        "api/vendas/",
        criar_venda,
        name="criar_venda",
    ),
]

vendas/urls.py
from django.urls import path

from .api.urls import api_urlpatterns
from .cliente.urls import cliente_urlpatterns
from .produto.urls import produto_urlpatterns
from .venda.urls import venda_urlpatterns
from .vendedor.urls import vendedor_urlpatterns
from .views import home

common_urls = [path("", home, name="home")]

# NOTE: incluir urlpatterns dos submodulos aqui para registralos no app
INCLUDE_URLS = (
    common_urls,
    cliente_urlpatterns,
    produto_urlpatterns,
    venda_urlpatterns,
    vendedor_urlpatterns,
    api_urlpatterns,
)

joined_urls = []
for urlpattern_list in INCLUDE_URLS:
    joined_urls.extend(urlpattern_list)

urlpatterns = joined_urls

vendas/venda/urls.py
from django.urls import path

from .views import (listar_vendas, nova_venda, selecionar_cliente,
                    selecionar_produto, selecionar_vendedor)

venda_urlpatterns = [
    path("vendas/", listar_vendas, name="listar_vendas"),
    path("vendas/nova-venda", nova_venda, name="nova_venda"),
    path(
        "vendas/selecionar_cliente",
        selecionar_cliente,
        name="selecionar_cliente",
    ),
    path(
        "vendas/selecionar_vendedor",
        selecionar_vendedor,
        name="selecionar_vendedor",
    ),
    path(
        "vendas/selecionar_produto",
        selecionar_produto,
        name="selecionar_produto",
    ),
]

vendas/models.py
from django.db import models


class Pessoa(models.Model):
    nome = models.CharField(max_length=255, null=False)
    cpf = models.CharField(max_length=11, null=False, unique=True)
    data_nascimento = models.DateField(null=False)

    def __str__(self) -> str:
        return f"id: {self.id}, nome: {self.nome}"

    class Meta:
        abstract = True

vendas/vendedor/models.py
from django.db import models

from ..models import Pessoa


class Vendedor(Pessoa):
    matricula = models.CharField(max_length=255, null=False, unique=True)
    data_contratacao = models.DateField(null=False)

    def __str__(self) -> str:
        return f"{super().__str__()}, matricula: {self.matricula}"

vendas/cliente/forms.py
from django import forms
from .models import Cliente,Endereco




class EnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = [
            "rua",
            "cidade",
            "estado",
            "cep",
        ]
        widgets = {
            "rua": forms.TextInput(
                attrs={"class": "form-control medium-input"}
            ),
            "cidade": forms.TextInput(
                attrs={"class": "form-control medium-input"}
            ),
            "estado": forms.TextInput(
                attrs={"class": "form-control medium-input"}
            ),
            "cep": forms.TextInput(
                attrs={
                    "class": "form-control medium-input",
                    "pattern": r"\d{8}",  # Supondo que o CEP tenha 8 dígitos
                    "title": "Formato inválido. Deve conter 8 dígitos.",
                }
            ),
        }


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nome", "cpf", "data_nascimento", "email", "telefone"]
        widgets = {
            "nome": forms.TextInput(
                attrs={"class": "form-control large-input"}
            ),
            "cpf": forms.TextInput(
                attrs={
                    "class": "form-control medium-input",
                    "pattern": r"\d{11}",
                    "title": "Formato inválido. Deve conter 11 dígitos.",
                }
            ),
            "data_nascimento": forms.DateInput(
                attrs={"type": "date", "class": "form-control medium-input"}
            ),
            "email": forms.EmailInput(
                attrs={"class": "form-control large-input"}
            ),
            "telefone": forms.TextInput(
                attrs={
                    "class": "form-control medium-input",
                    "pattern": r"\d{8,15}",  # Ajustado para um formato de telefone mais comum
                    "title": "Formato inválido. Deve conter entre 8 e 15 dígitos.",
                }
            ),
        }

vendas/produto/forms.py
from django import forms


class ProdutoForm(forms.Form):
    nome = forms.CharField(
        label="Nome do Produto",
        max_length=255,
        required=True,
    )
    preco = forms.DecimalField(
        label="Preço do Produto",
        min_value=0,
        decimal_places=2,
        required=True,
    )
    cor = forms.CharField(
        label="Cor do Produto",
        max_length=255,
        required=True,
    )
    tamanho = forms.CharField(
        label="Tamanho do Produto",
        max_length=255,
        required=True,
    )
    referencia = forms.CharField(
        label="Referência do Produto",
        max_length=255,
        required=False,
    )

vendas/api/views.py
from django.contrib import messages
from django.http import HttpRequest, JsonResponse
from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser, ParseError

from ..produto.models import Produto
from ..produto.serializers import ProdutoReadSerializer
from ..venda.serializers import VendaWriteSerializer


class ProdutoDetalheView(generics.RetrieveAPIView):
    queryset = Produto.objects.all()
    serializer_class = ProdutoReadSerializer
    lookup_field = "id"


@api_view(["POST"])
def criar_venda(request: HttpRequest):
    try:
        serializer = VendaWriteSerializer(data=JSONParser().parse(request))

    except ParseError:
        messages.error(request=request, message="Erro ao finalizar a venda!")
        return JsonResponse({"detail": "Invalid JSON"}, status=400)

    if not serializer.is_valid():
        messages.error(request=request, message="Erro ao finalizar a venda!")
        return JsonResponse(serializer.errors, status=400)

    messages.success(request=request, message="Venda concluida com sucesso!")
    serializer.save()
    return JsonResponse(serializer.data, status=201)

vendas/cliente/views.py
import logging

from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from .forms import ClienteForm,EnderecoForm,Cliente,Endereco
from django.urls import reverse
from django.contrib import messages
from django.http import JsonResponse

logger = logging.getLogger(__name__)


def listar_clientes(request: HttpRequest) -> render:
    clientes = Cliente.objects.all()
    return render(
        request,
        "vendas/cliente/listar_clientes.html",
        {"clientes_list": clientes},
    )


def criar_cliente(request: HttpRequest) -> render:
    if request.method == "POST":
        cliente_form = ClienteForm(request.POST)
        endereco_form = EnderecoForm(request.POST)

        if cliente_form.is_valid() and endereco_form.is_valid():
            try:
                endereco = endereco_form.save()  # Salva primeiro o endereço
                cliente = cliente_form.save(commit=False)
                cliente.endereco = endereco  # Associa o endereço ao cliente
                cliente.save()
                messages.success(request=request,
                                 message="Cliente criado com sucesso!")
            except Exception as e:
                logger.exception(msg=e)
                messages.error(request=request,
                                 message="Erro ao criar cliente!")
            finally:
                return redirect(
                    "criar_cliente"
                )  # Redireciona para a lista de clientes

    else:
        cliente_form = ClienteForm()
        endereco_form = EnderecoForm()

    return render(
        request,
        "vendas/cliente/criar_cliente.html",
        {"cliente_form": cliente_form, "endereco_form": endereco_form},
    )


def editar_cliente(request: HttpRequest, cliente_id: int) -> render:
    cliente = get_object_or_404(Cliente, id=cliente_id)
    endereco = get_object_or_404(Endereco, id=cliente_id)

    if request.method == "POST":
        cliente_form = ClienteForm(request.POST, instance=cliente)
        endereco_form = EnderecoForm(request.POST, instance=endereco)
        if cliente_form.is_valid() and endereco_form.is_valid():
            try:
                cliente_form.save()
                endereco_form.save()
                messages.success(request=request,
                                 message="Cliente editado com sucesso!")
            except Exception as e:
                logger.exception(msg=e)
                messages.error(
                    request=request,
                    message = "Erro ao editar cliente"
                               )
            finally:
                return redirect(reverse('editar_cliente', args=[cliente_id]))
    else:
        cliente_form = ClienteForm(instance=cliente)
        endereco_form = EnderecoForm(instance=endereco)

    return render(
        request,
        "vendas/cliente/editar_cliente.html",
        {
            "cliente_form": cliente_form,
            "endereco_form": endereco_form,
            "delete_url": reverse(
                viewname="deletar_cliente",
                kwargs={"cliente_id": cliente_id},
            ),
        },
    )

 
def deletar_cliente(request: HttpRequest, cliente_id: int):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    endereco = get_object_or_404(Endereco, id=cliente_id)
    clientes = Cliente.objects.all()
    
    if request.method == "POST":
        try:
            cliente.delete()
            endereco.delete()
            messages.success(request, "Cliente deletado com sucesso!")
        except Exception as e:
            logger.exception(msg=e)
            messages.error(request, "Erro ao deletar cliente!")
    
    return render(
            request,
            "vendas/cliente/listar_clientes.html",
            {"clientes_list": clientes},
        )
 

def obter_nome_cliente(request: HttpRequest)-> JsonResponse:
    if request.method == 'GET':
        cliente_id = request.GET.get('cliente_id')  # Obtém o cliente_id da requisição GET
        try:
            cliente = Cliente.objects.get(id=cliente_id)
            return JsonResponse({'nome_cliente': cliente.nome})
        except Cliente.DoesNotExist:
            return JsonResponse({'error': 'Cliente não encontrado'}, status=404)
    else:
        return JsonResponse({'error': 'Método não suportado'}, status=405)

vendas/produto/views.py
import logging

from django.contrib import messages
from django.http import (HttpRequest, HttpResponse, HttpResponseNotAllowed,
                         HttpResponseRedirect, JsonResponse)
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import ProdutoForm
from .models import Produto

logger = logging.getLogger(__name__)


def listar_produtos(request: HttpRequest) -> HttpResponse:
    produtos = Produto.objects.all()
    return render(
        request=request,
        template_name="vendas/produto/listar_produtos.html",
        context={"produtos": produtos},
    )


def criar_produto(request: HttpRequest) -> render:
    if request.method == "POST":
        form = ProdutoForm(request.POST)
        if form.is_valid():
            try:
                novo_produto = Produto(
                    nome=form.cleaned_data["nome"],
                    preco=form.cleaned_data["preco"],
                    cor=form.cleaned_data["cor"],
                    tamanho=form.cleaned_data["tamanho"],
                    referencia=form.cleaned_data["referencia"],
                )
                novo_produto.save()
                messages.success(
                    request=request,
                    message="Produto criado com sucesso!",
                )
            except Exception as e:
                logger.exception(msg=e)
                messages.error(
                    request=request,
                    message="Erro ao criar produto",
                )
            finally:
                return redirect("listar_produtos")
    else:
        form = ProdutoForm()
        return render(
            request=request,
            template_name="vendas/produto/criar_produto.html",
            context={"form": form},
        )


def editar_produto(
    request: HttpRequest, produto_id: int
) -> HttpResponse | HttpResponseRedirect:
    produto = get_object_or_404(klass=Produto, id=produto_id)

    initial_data = {
        "nome": produto.nome,
        "preco": produto.preco,
        "cor": produto.cor,
        "tamanho": produto.tamanho,
        "referencia": produto.referencia,
    }

    if request.method != "POST":
        form = ProdutoForm(initial=initial_data)
        return render(
            request=request,
            template_name="vendas/produto/editar_produto.html",
            context={
                "form": form,
                "delete_url": reverse(
                    viewname="deletar_produto",
                    kwargs={"produto_id": produto_id},
                ),
            },
        )

    form = ProdutoForm(data=request.POST, initial=initial_data)

    if not form.has_changed() or not form.is_valid():
        return redirect("editar_produto", produto_id=produto_id)

    try:
        for field in form.changed_data:
            setattr(produto, field, form.cleaned_data[field])
        produto.save()
        messages.success(
            request=request,
            message="Produto editado com sucesso!",
        )
    except Exception as e:
        logger.exception(msg=e)
        messages.error(
            request=request,
            message="Erro ao editar produto",
        )
    finally:
        return redirect("editar_produto", produto_id=produto_id)


def deletar_produto(
    request: HttpRequest, produto_id: int
) -> HttpResponseRedirect | HttpResponseNotAllowed:
    produto = get_object_or_404(klass=Produto, id=produto_id)

    if request.method != "POST":
        return HttpResponseNotAllowed(permitted_methods=["POST"])

    try:
        produto.delete()
        messages.success(
            request=request, message="Produto deletado com sucesso!"
        )
    except Exception as e:
        logger.exception(msg=e)
        messages.error(
            request=request,
            message="Erro ao deletar produto",
        )
    finally:
        return redirect("listar_produtos")


def obter_nome_produto(request: HttpRequest) -> render:
    if request.method == "GET":
        produto_id = request.GET.get("produto_id")
        try:
            produto = Produto.objects.get(id=produto_id)
            return JsonResponse({"nome_produto": produto.nome})
        except Produto.DoesNotExist:
            return JsonResponse({"error": "Produto não encontrado"}, status=404)
    else:
        return JsonResponse({"error": "Método não suportado"}, status=405)


def obter_preco_produto(request: HttpRequest) -> render:
    if request.method == "GET":
        produto_id = request.GET.get("produto_id")
        try:
            produto = Produto.objects.get(id=produto_id)
            return JsonResponse({"preco_produto": produto.preco})
        except Produto.DoesNotExist:
            return JsonResponse({"error": "Produto não encontrado"}, status=404)
    else:
        return JsonResponse({"error": "Método não suportado"}, status=405)

vendas/venda/views.py
from django.http import HttpRequest
from django.shortcuts import render

from ..cliente.models import Cliente
from ..produto.models import Produto
from ..vendedor.models import Vendedor
from .models import Venda


def nova_venda(request: HttpRequest) -> render:
    return render(request, "vendas/venda/nova_venda.html")


def listar_vendas(request: HttpRequest):
    vendas = Venda.objects.all().order_by("-data_venda")
    return render(
        request=request,
        template_name="vendas/venda/listar_vendas.html",
        context={"vendas": vendas},
    )


def selecionar_cliente(request: HttpRequest) -> render:
    clientes = Cliente.objects.all()
    return render(
        request,
        "vendas/cliente/selecionar_cliente.html",
        {"clientes": clientes},
    )


def selecionar_vendedor(request: HttpRequest) -> render:
    vendedores = Vendedor.objects.all()
    return render(
        request,
        "vendas/vendedor/selecionar_vendedor.html",
        {"vendedores": vendedores},
    )


def selecionar_produto(request: HttpRequest) -> render:
    produtos = Produto.objects.all()
    return render(
        request,
        "vendas/produto/selecionar_produto.html",
        {"produtos": produtos},
    )

vendas/views.py
from django.http import HttpRequest
from django.shortcuts import render


def home(request: HttpRequest) -> render:
    return render(request, "vendas/home.html")

vendas/templates/vendas/vendedor/criar_vendedor.html
{% extends 'vendas/partials/base.html' %}
{% comment %}

TODO: Ajustar as boxes 

{% endcomment %}
{% block content %}
<div style="background-color: #f4f4f4; min-height: 50vh; display: flex; justify-content: center; align-items: center; padding: 10px;">

    <div style="min-height:50vh;background-color: #fff; border-radius: 10px; box-shadow: 0 0 20px rgba(0, 0, 0, 0.1); width: 100%; max-width: 1400px; padding: 20px; text-align: left;">

        <h1 style="font-size: 2em; margin-bottom: 20px; color: #3498db;">Cadastro de Vendedor</h1>

        {% include 'vendas/vendedor/form_vendedor.html' %}
    </div>

</div>
{% endblock %}

vendas/templates/vendas/vendedor/editar_vendedor.html
{% extends 'vendas/partials/base.html' %}
{% comment %}

TODO: Ajustar as boxes 

{% endcomment %}
{% block content %}
<div class="d-flex justify-content-between mb-2">
    <h3>Editar vendedor</h3>
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal">Deletar</button>
</div>
<div style="background-color: #f4f4f4; min-height: 50vh; display: flex; justify-content: center; align-items: center; padding: 10px;">

    <div style="min-height:50vh;background-color: #fff; border-radius: 10px; box-shadow: 0 0 20px rgba(0, 0, 0, 0.1); width: 100%; max-width: 1400px; padding: 20px; text-align: left;">

        {% include 'vendas/vendedor/form_vendedor.html' %}
    </div>

</div>
{% include 'vendas/partials/modal.html' with form_action_url=delete_url title='Deletar vendedor' body='Deseja realmente deletar este vendedor?' btn_text='Deletar' btn_class='danger' %}
{% endblock %}

vendas/templates/vendas/vendedor/form_vendedor.html
<form method="post">
    {% csrf_token %}

    <div style="display: grid; gap: 20px; grid-template-columns: 1fr 1fr;">

        <div style="grid-column: span 1 ;">
            <label for="id_nome" style="font-size: 1.2em; color: #333; margin-bottom: 5px; display: block;">Nome:</label>
            {{ form.nome }}
            {% include 'vendas/partials/form_field_errors.html' with errors=form.nome.errors %}
        </div>

        <div style = "margin-left:50px;">
            <label for="id_matricula" style="font-size: 1.2em; color: #333; margin-bottom: 5px; display: block;">Matrícula:</label>
            {{ form.matricula }}
            {% include 'vendas/partials/form_field_errors.html' with errors=form.matricula.errors %}
        </div>

        <div style="display: grid; gap: 50px; grid-template-columns: repeat(3, 1fr);grid-column: span 2 ;">
            <div>
                <label for="id_data_nascimento" style="font-size: 1.2em; color: #333; margin-bottom: 5px; display: block;">Data de Nascimento:</label>
                {{ form.data_nascimento }}
                {% include 'vendas/partials/form_field_errors.html' with errors=form.data_nascimento.errors %}
            </div>

            <div>
                <label for="id_cpf"style="font-size: 1.2em; color: #333; margin-bottom: 5px; display: block;">CPF:</label>
                {{ form.cpf }}
                {% include 'vendas/partials/form_field_errors.html' with errors=form.cpf.errors %}
            </div>

            <div>
                <label for="id_data_contratacao" style="font-size: 1.2em; color: #333; margin-bottom: 5px; display: block;">Data de Contratação:</label>
                {{ form.data_contratacao }}
                {% include 'vendas/partials/form_field_errors.html' with errors=form.data_contratacao.errors %}
            </div>
        </div>

        <div style="display: flex; align-items: flex-end; margin-top: 20px;">
            <button class='btn btn-primary btn-lg' type="submit" style="margin-left: auto;">Salvar</button>
            <button class='btn btn-danger btn-lg' type="button" onclick="location.href='{% url 'listar_vendedores' %}'" style="margin-left: 10px;">Sair</button>
        </div>
    </div>

</form>

vendas/templates/vendas/vendedor/listar_vendedores.html
{% extends 'vendas/partials/base.html' %}

{% block content %}
  <div class="d-flex justify-content-between">
    <h3>Vendedores</h3>
    <a class="btn btn-success" href="{% url 'criar_vendedor' %}" role="button">Criar</a>
  </div>
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">Data de Nascimento</th>
        <th scope="col">Matrícula</th>
        <th scope="col">Data de Contratação</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for vendedor in vendedores_list %}
        <tr>
          <td>{{ vendedor.id }}</td>
          <td>{{ vendedor.nome }}</td>
          <td>{{ vendedor.cpf }}</td>
          <td>{{ vendedor.data_nascimento|date:'SHORT_DATE_FORMAT' }}</td>
          <td>{{ vendedor.matricula }}</td>
          <td>{{ vendedor.data_contratacao|date:'SHORT_DATE_FORMAT' }}</td>
          <td>
            <a class="btn btn-primary" href="{% url 'editar_vendedor' vendedor.id %}" role="button">Editar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

vendas/templates/vendas/vendedor/selecionar_vendedor.html
{% extends 'vendas/partials/base.html' %}

{% block content %}
<div class="container">
    <h3 id="XX">Selecione um Vendedor</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nome</th>
                <th>CPF</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for vendedor in vendedores %}
            <tr>
                <td>{{ vendedor.nome }}</td>
                <td>{{ vendedor.cpf }}</td>
                <td>
                    <button class="btn btn-primary" onclick="selecionarVendedor('{{ vendedor.id }}')">Selecionar</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    function selecionarVendedor(id) {
        localStorage.setItem('vendedorId', id);
        window.location.href = '{% url 'nova_venda' %}';
    }
</script>
{% endblock %}